version: '3.7'

services:

  caddy:
    container_name: caddy
    image: caddy:2-alpine
    restart: on-failure
    networks:
      - searx
    ports:
      - "${SEARX_HTTP_PORT:-80}:80"
      - "${SEARX_HTTPS_PORT:-443}:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data:rw
      - caddy-config:/config:rw
    environment:
      - SEARX_HOSTNAME=${SEARX_HOSTNAME:-localhost}
      - SEARX_TLS=${LETSENCRYPT_EMAIL:-internal}
      - PROTOCOL_OVERRIDE=${PROTOCOL_OVERRIDE:-}
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - DAC_OVERRIDE

  filtron:
    container_name: filtron
    image: dalf/filtron
    restart: always
    networks:
      - searx
    ports:
      - 4041:4041
    command: -listen 0.0.0.0:4040 -api 0.0.0.0:4041 -target searx:8080
    volumes:
      - ./rules.json:/etc/filtron/rules.json:rw
    read_only: true
    cap_drop:
      - ALL

  searx:
    container_name: searx
    image: searx/searx:latest
    restart: always
    networks:
      - searx
    command: ${SEARX_COMMAND:-}
    volumes:
      - ./searx:/etc/searx:rw
    environment:
      - BIND_ADDRESS=0.0.0.0:8080
      - BASE_URL=${PROTOCOL_OVERRIDE:-}${SEARX_HOSTNAME}/
      - MORTY_URL=${PROTOCOL_OVERRIDE:-}${SEARX_HOSTNAME}/morty/
      - MORTY_KEY=${MORTY_KEY}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  morty:
    container_name: morty
    image: dalf/morty
    restart: always
    networks:
      - searx
    command: -timeout 6 -ipv6
    environment:
      - MORTY_KEY=${MORTY_KEY}
      - MORTY_ADDRESS=0.0.0.0:3000
    logging:
      driver: none
    read_only: true
    cap_drop:
      - ALL

  searx-checker:
    container_name: searx-checker
    image: searx/searx-checker
    restart: always
    networks:
      - searx
    command: -cron -o html/data/status.json ${PROTOCOL_OVERRIDE:-}searx:8080
    volumes:
      - checker-data:/usr/local/searx-checker/html/data

networks:
  searx:
    ipam:
      driver: default

volumes:
  caddy-data:
  caddy-config:
  checker-data:
